accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts.views import OrganizationListView, index

urlpatterns = [
    path('', index, name='index'),
    path('organizations/', OrganizationListView.as_view(), name='organizations'),
]

composeexample/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

core/urls.py
from django.conf.urls import include, url

import core.views


urlpatterns = [
    # Core views
    url(
        r'^history/(?P<content_type>[0-9]+)/(?P<object_id>[0-9]+)/',
        core.views.ObjectHistoryView.as_view(),
        name='history'
    ),

    # Scan barcodes
    url(r'^scan/', include([
        url(r'^modal/$', core.views.ScannerModalView.as_view(), name='scanner_modal'),
    ])),
]

handler403 = core.views.PermissionErrorView.as_view()
handler404 = core.views.PageNotFoundErrorView.as_view()
handler500 = core.views.ServerErrorView.as_view()

accounts/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Organization(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=255)
    description = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    creator = models.TextField()


    def get_absolute_url(self):
        return reverse('organization_detail', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Organization, self).save(*args, **kwargs)


    class Meta:
        ordering = ['created_on']

        def __unicode__(self):
            return self.name

core/models.py
from django.contrib.auth.models import Group, User
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from guardian.models import GroupObjectPermission, UserObjectPermission

from core.utils.display import get_datetime_display


class ResourceStatisticsManager(models.Manager):
    def get_for_resource(self, resource):
        stats, _ = super(ResourceStatisticsManager, self).get_queryset().get_or_create(
            resource_content_type=ContentType.objects.get_for_model(resource),
            resource_object_id=resource.id
        )
        return stats


class ResourceStatistics(models.Model):
    class Meta:
        unique_together = (('resource_content_type', 'resource_object_id'), )
    # Custom manager for easy lookup
    objects = ResourceStatisticsManager()

    # What is this CostCenter being attributed towards
    resource_content_type = models.ForeignKey(ContentType)
    resource_object_id = models.PositiveIntegerField()
    resource = GenericForeignKey('resource_content_type', 'resource_object_id')

    # DateTime resounce was created
    date_created = models.DateTimeField(db_index=True, auto_now_add=True, editable=False)

    # DateTime resource was last changed
    date_modified = models.DateTimeField(auto_now=True, editable=False)

    # User we triggered creation of the resource
    created_by = models.ForeignKey(User, null=True, editable=False)

    def get_date_created_display(self):
        return get_datetime_display(self.date_created)

    def __unicode__(self):
        return '%s %s' % (unicode(self.resource_content_type).title(), unicode(self.resource))


class VisualModel(object):
    # DO NOT REMOVE UNTIL MIGRATION SQUASH HAPPENS
    # This code is kept to maintain backwards compatability
    pass


class ManagedModel(models.Model):
    class Meta:
        abstract = True
        permissions = (
            ('owner', 'Grants full access'),
        )
        default_permissions = ('add', 'change', 'delete', 'view')

    statistics = GenericRelation(
        ResourceStatistics,
        related_query_name='statistics',
        content_type_field='resource_content_type',
        object_id_field='resource_object_id'
    )

    def date_created(self):
        return self.get_statistics().date_created
    date_created.short_description = 'Date created'

    def get_statistics(self):
        '''Attempts to get the potentially prefetched ResourceStatistics.

        Provides a fallback with a get_or_create since this object should always exist.
        '''
        try:
            return self.statistics.all()[0]
        except IndexError:
            pass
        return ResourceStatistics.objects.get_for_resource(self)

    # Returns a list of groups which can access this resource
    def get_groups_access(self, **kwargs):
        kwargs.update({
            'object_pk': self.pk,
            'content_type': ContentType.objects.get_for_model(self)
        })

        # Perform the query
        return Group.objects.filter(
            id__in=GroupObjectPermission.objects.filter(
                **kwargs
            ).values_list('group_id', flat=True)
        )

    # Returns a list of groups which have explicit access to this resource
    # TODO: Does users list need to include those who have access through a group, or just explicit user access?
    def get_users_access(self):
        # Perform the query
        return User.objects.filter(
            id__in=UserObjectPermission.objects.filter(
                object_pk=self.pk,
                content_type=ContentType.objects.get_for_model(self)
            ).values_list('user_id', flat=True)
        )

    @property
    def creator(self):
        return self.get_statistics().created_by

    def get_creator_display(self):
        creator = self.creator
        if creator is not None:
            return creator.get_full_name()
        return 'SYSTEM'

core/forms.py
from django import forms
from django.contrib.postgres import forms as pg_forms


class ScannerForm(forms.Form):
    barcode = forms.CharField(max_length=64)

    def clean_barcode(self):
        return self.cleaned_data['barcode'].strip()


class SingleObjectActionForm(forms.ModelForm):
    class Meta:
        fields = []

    perform = forms.BooleanField(widget=forms.HiddenInput())


class DisableSimpleArrayField(pg_forms.SimpleArrayField):
    def clean(self, value):
        # Corrects a bug that occurs when the field is disabled on the form
        if isinstance(value, list):
            return value

        return super(DisableSimpleArrayField, self).clean(value)

accounts/views.py
from django.shortcuts import render
import os.path
from django_tables2 import SingleTableView
from django.conf import settings
from django.forms import modelformset_factory
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.views import generic
from accounts.models import Organization
from .tables import OrganizationTable

# Create your views here.


def index(request):
    return HttpResponse("Hello, world.")


class OrganizationListView(SingleTableView):
    '''`Organizations` list view.
    '''
    model = Organization
    queryset = Organization.objects.all()
    table_class = OrganizationTable
    template_name = 'accounts/organization_list.html'
    # filterset_class = FamilyFilter
    # paginate_by = 25
    # permission_required = ('clinical.view_family', )
    # table_pagination = {'per_page': paginate_by}

    # export_filename = 'families'
    # export_template_name = 'genepeeks/components/table.tsv'
    # staff_role = GenePeeksStaff
    # staff_only_fields = ('members', 'date_of_birth', )

    # return HttpResponse("Hello, world. You're at the polls fuck that.")

    def get_table_data(self):
        return self.object_list

# class OrganizationCreateView(HostLoginRequiredMixin, RoleRequiredMixin, AtomicTransactionMixin, generic.CreateView):
#     '''Onboarding view for all base `Organizations` in the system.
#     '''
#     model = Organization
#     form_class = OrganizationCreateForm
#     role_required = (Admin, GenePeeksStaff)
#     template_name = 'accounts/organization_create.html'

accounts/templates/accounts/base.html
{% extends 'core/generics/base-detail.html' %}

{% load core_filters %}
{% load hosts %}
{% load icons %}
{% load staticfiles %}

{% block accounts-app-navigation %}active{% endblock %}
{% block accounts-app-navigation-arrow %}open{% endblock %}

{% block css-imports %}
    {{ block.super }}
    <link href='{% static 'accounts/css/accounts.css' %}' rel='stylesheet' type='text/css' />
{% endblock %}

{% block page-subtitle %}Profile & Settings{% endblock %}

{% block page-content %}
    <div class='row'>
        <div class='col-md-12'>

            <!-- BEGIN PROFILE SIDEBAR -->
            <div class='profile-sidebar'>
                <!-- PORTLET MAIN -->
                <div class='portlet light profile-sidebar-portlet bordered'>
                    <!-- SIDEBAR AVATAR -->
                    <div class='profile-userpic'>
                        {% block sidebar-avatar %}
                            <img src='{% static 'core/images/GenePeeks_Iconography_primary-44.svg' %}' class='img-responsive' alt=''>
                        {% endblock %}
                    </div>
                    <!-- END SIDEBAR AVATAR -->
                    <!-- SIDEBAR TITLE -->
                    <div class='profile-usertitle'>
                        {% block sidebar-title %}{% endblock %}
                    </div>
                    <!-- END SIDEBAR TITLE -->

                    <!-- SIDEBAR MENU -->
                    <div class='profile-usermenu'>
                        <ul class='nav'>
                            <li>
                                <a href='{% block sidebar-menu-detail-url %}{% endblock %}'>
                                    <i class='glyphicons glyphicons-home'></i> Overview
                                </a>
                            </li>
                            <li>
                                <a href='{% block sidebar-menu-settings-url %}{% endblock %}'>
                                    <i class='glyphicons glyphicons-cogwheel'></i> Settings
                                </a>
                            </li>
                            {% block sidebar-menu-extra-items %}{% endblock %}
                        </ul>
                    </div>
                    <!-- END MENU -->
                </div>
                <!-- END PORTLET MAIN -->
                {% block sidebar-stat %}{% endblock %}
            </div>
            <!-- END BEGIN PROFILE SIDEBAR -->

            <!-- BEGIN PROFILE CONTENT -->
            {% block profile-content %}
                <div class='profile-content'>
                    <div class='row'>
                        <div class='col-md-12'>
                            <div class='portlet light'>
                                <div class='portlet-title tabbable-line'>
                                    <div class='caption caption-md'>
                                        <i class='icon-globe theme-font hide'></i>
                                        <span class='caption-subject font-blue-madison bold uppercase'>{% block profile-content-title %}{% endblock %}</span>
                                    </div>
                                    <div class='actions'>
                                        {% with content_type=object|content_type %}
                                            {% block detail-actions-edit %}
                                                {# Edit Object Icon #}
                                                {% large_action_icon 'glyphicons-pencil' tooltip_message='Edit '|add:content_type.model|title %}
                                            {% endblock %}

                                            {% block detail-model-actions %}
                                                {% if roles.gene_peeks_staff %}
                                                    {% if request.user.is_staff %}
                                                    {# Edit on Admin Site Icon #}
                                                        {% host_url 'admin:'|add:content_type.app_label|add:'_'|add:content_type.model|add:'_change' object.pk host 'dashboard' as admin_edit_url %}
                                                        {% large_action_icon 'glyphicons-database' url=admin_edit_url tooltip_message='Edit on Admin' %}
                                                    {% endif %}
                                                {% endif %}
                                            {% endblock %}
                                        {% endwith %}

                                        {% block detail-actions %}{% endblock %}
                                    </div>
                                </div>
                                <div class='portlet-body'>
                                    <div class='row'>
                                        <div class='col-xs-12 col-sm-8 col-lg-6'>
                                            <div class='list-group'>
                                                {% block profile-content-body %}{% endblock %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endblock %}
            <!-- END PROFILE CONTENT -->
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/columns/organization_name_column.html
{% load hosts %}

<a href='{% host_url 'organization:detail' pk=record.pk host 'accounts' %}'>{{ record.name }}</a>

accounts/templates/accounts/columns/organizations_column.html
{% load organization_filters %}

{{ record|get_organizations|join:', ' }}

accounts/templates/accounts/columns/roles_column.html
{% load role_filters %}

{% with roles=record|get_roles %}
    {{ roles|slice:":3"|join:', ' }}{% if roles|length > 3 %} ...{% endif %}
{% endwith %}

accounts/templates/accounts/columns/user_active_column.html
{% if record.invite and not record.invite.date_expired %}Pending{% else %}{{ record.is_active }}{% endif %}

accounts/templates/accounts/columns/user_name_column.html
{% load hosts %}

<a href='{{ record.get_absolute_url }}'>{{ record.get_full_name|default:record.username }}</a>

accounts/templates/accounts/create/internal_user_create.html
{% extends 'core/generics/base-create.html' %}

{% load django_bootstrap_breadcrumbs %}
{% load hosts %}

{% block breadcrumb-tags %}
    {% breadcrumb 'Accounts' 'root' %}
    {% breadcrumb 'Users' 'user:list' %}
    {% breadcrumb 'Create' '' %}
{% endblock %}

{% block html-title %}Create User{% endblock %}

{% block page-title %}User{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base_form.html' %}

{% load crispy_forms_tags %}
{% load hosts %}
{% load staticfiles %}

{% block html-title %}Login{% endblock %}

{% block form %}
    <form id='login-form' action='{% host_url 'login' host 'accounts' %}?{{ query_string }}' method='POST'>{% csrf_token %}
        <a href='{{ google_url }}?{{ query_string }}'>
            <img id='google-icon' src='{% static 'accounts/img/btn_google_signin.png' %}' />
        </a>

        <div class='or-option'>-- or --</div>

        {% include 'accounts/partials/_messages.html' %}

        {{ form|crispy }}

        <div id='login-button-container' class='form-group'>
            <button type='submit' class='btn btn-inverse'>Sign In</button>
        </div>
        <div id='login-alt-container'>
            <a id='forgot_button' href='{% host_url 'forgot_password' host 'accounts' %}?{{ query_string }}'>Forgot password?</a>
            <br/><br/>
            Don't have an account? <a href='{% host_url 'create_user' host 'accounts' %}?{{ query_string }}'>Sign Up</a>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/organization_base.html
{% extends 'accounts/base.html' %}

{% load django_bootstrap_breadcrumbs %}
{% load hosts %}

{% block breadcrumb-tags %}
    {% breadcrumb 'Accounts' 'root' %}
    {% breadcrumb 'Organizations' 'organization:list' %}
    {% breadcrumb organization.name 'organization:detail' pk=organization.pk %}
{% endblock %}

{% block html-title %}{{ organization.name }}'s Profile{% endblock %}

{% block page-title %}{{ organization.name }}{% endblock %}

{% block sidebar-title %}
    <div class='profile-usertitle-name'>{{ organization.name }}</div>
    <div class='profile-usertitle-job'>
        {% with members_count=organization.members_order_by_last_login.count %}
            <a href='{% host_url 'user:list' host 'accounts' %}?organization={{ organization.pk }}'>{{ members_count }} Member{% if members_count != 1 %}s{% endif %}</a>
        {% endwith %}
    </div>
    <br/>
    {% if organization.website %}
        <div class='profile-stat-title'>{{ organization.website|urlize }}</div>
    {% endif %}
    {% if organization.address %}
        <div class='profile-stat-title'>{{ organization.address }}</div>
    {% endif %}
    {% if organization.phone_number %}
        <div class='profile-stat-title'>{{ organization.get_phone_number_display }}</div>
    {% endif %}
    <br/>
{% endblock %}

{% block sidebar-menu-detail-url %}{% host_url 'organization:detail' pk=organization.pk host 'accounts' %}{% endblock %}

{% block sidebar-menu-settings-url %}{% host_url 'organization:settings:detail' pk=organization.pk host 'accounts' %}{% endblock %}

{% block sidebar-menu-extra-items %}
    {% if organization.bank %}
        <li>
            <a href='{% host_url 'organization:bank:detail' pk=organization.pk division='bank' host 'accounts' %}'>
                <i class='glyphicons glyphicons-gender-intersex'></i> Bank
            </a>
        </li>
    {% endif %}
    {% if organization.clinic %}
        <li>
            <a href='{% host_url 'organization:clinic:detail' pk=organization.pk division='clinic' host 'accounts' %}'>
                <i class='glyphicons glyphicons-doctor'></i> Clinic
            </a>
        </li>
    {% endif %}
    {% if organization.lab %}
        <li>
            <a href='{% host_url 'organization:lab:detail' pk=organization.pk division='lab' host 'accounts' %}'>
                <i class='glyphicons glyphicons-lab'></i> Lab
            </a>
        </li>
    {% endif %}
{% endblock %}

accounts/templates/accounts/organization_detail.html
{% extends 'accounts/organization_base.html' %}

{% load hosts %}
{% load mathfilters %}
{% load notes %}
{% load staticfiles %}

{% block user-detail-menu-overview %}active{% endblock %}

{% block profile-content %}
    <div class='profile-content'>
        <div class='row'>
            <div class='col-lg-6'>
                <!-- BEGIN PORTLET -->
                <div class='portlet light bordered'>
                    <div class='portlet-title'>
                        <div class='caption caption-md'>
                            <i class='icon-bar-chart theme-font hide'></i>
                            <span class='caption-subject font-blue-madison bold uppercase'>{{ organization.name }}'s Team</span>
                        </div>
                        {% if perms.auth.add_user %}
                            <div class='page-actions actions'>
                                <div class='btn-group'>
                                    <a href='{% host_url 'organization:invite' pk=organization.pk host 'accounts' %}' class='btn btn-sm red-haze' data-toggle='modal' data-target="#dynamic-modal">
                                        Add User
                                    </a>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <div class='portlet-body'>
                        <div class='table-scrollable table-scrollable-borderless'>
                            <table class='table table-hover table-light'>
                                <thead>
                                    <tr class='uppercase'>
                                        <th colspan='2'>MEMBER</th>
                                        <th>ACTIVE</th>
                                        <th>EMAIL</th>
                                        <th>LAST SEEN</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% with members=organization.members_order_by_last_login members_count=organization.members_order_by_last_login.count %}
                                        {% for member in members|slice:':5' %}
                                            <tr>
                                                <td class='fit'>
                                                    <img class='user-pic' src='{% if member.profile.icon %}{{ member.profile.icon }}{% else %}{% static 'core/images/GenePeeks_Iconography_primary-44.svg' %}{% endif %}'>
                                                </td>
                                                <td>
                                                    <a href='{% host_url 'user:detail' pk=member.pk host 'accounts' %}' class='primary-link'>{{ member.first_name }}</a>
                                                </td>
                                                <td>
                                                    {% with record=member %}
                                                        {% include 'accounts/columns/user_active_column.html' %}
                                                    {% endwith %}
                                                </td>
                                                <td><a href='mailto:{{ member.email }}'>{{ member.email }}</a></td>
                                                <td>{{ member.last_login }}</td>
                                            </tr>
                                        {% endfor %}

                                        {% if members_count > 5 %}
                                            <tr>
                                                <td colspan='4'>
                                                    <p class='text-center' style='padding-top: 10px;'>
                                                        <a href='{% host_url 'user:list' host 'accounts' %}?organization={{ organization.pk }}'>And {{ members_count|sub:5 }} more users...</a>
                                                    </p>
                                                </td>
                                            </tr>
                                        {% endif %}
                                    {% endwith %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- END PORTLET -->
            </div>
            <div class='col-md-6'>
                <div class="portlet light portlet-fit bordered">
                    <div class="portlet-title">
                        <div class="caption caption-md">
                            <i class="icon-bar-chart theme-font hide"></i>
                            <span class="caption-subject font-blue-madison bold uppercase">Notes</span>
                        </div>
                    </div>
                    <div class="portlet-body" style="max-height: 600px; overflow: auto;">
                        {% render_notes organization %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/organization_settings_clinic_detail.html
{% extends 'accounts/organization_base.html' %}

{% load django_bootstrap_breadcrumbs %}
{% load hosts %}
{% load icons %}
{% load primitive_types %}

{% block breadcrumb-tags %}
    {{ block.super }}
    {% breadcrumb 'Clinic' 'organization:clinic:detail' pk=organization.pk division='clinic' %}
{% endblock %}

{% block profile-content-title %}Clinic Settings{% endblock %}

{% block detail-actions-edit %}
    {% if perms.gist.change_clinic %}
        {% host_url 'organization:clinic:update' pk=organization.pk division='clinic' host 'accounts' as url %}
        {% large_action_icon 'glyphicons-pencil' tooltip_message='Edit Clinic' %}
    {% endif %}
{% endblock %}

{% block profile-content-body %}
    <div class='list-group-item'>
        <h4 class='list-group-item-heading'>Active</h4>
        <p class='list-group-item-text'>
            {% boolean organization.clinic.active %}
        </p>
    </div>
{% endblock %}

accounts/templates/accounts/organization_settings_clinic_update.html
{% extends 'accounts/organization_settings_clinic_detail.html' %}

{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% load hosts %}
{% load icons %}

{% block breadcrumb-tags %}
    {{ block.super }}
    {% breadcrumb 'Update' 'organization:clinic:update' pk=organization.pk division='clinic' %}
{% endblock %}

{% block profile-content-title %}Clinic Settings{% endblock %}

{% block detail-actions-edit %}
    {% if perms.gist.change_clinic %}
        {% host_url 'organization:clinic:update' pk=organization.pk division='clinic' host 'accounts' as url %}
        {% large_action_icon 'glyphicons-pencil' tooltip_message='Edit Clinic' %}
    {% endif %}
{% endblock %}

{% block profile-content-body %}
    <form method='POST' action="{% host_url 'organization:clinic:update' division='clinic' pk=organization.pk host 'accounts' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <button type='submit' class='btn blue' name='Submit' value='Submit'>Submit</button>
    </form>
{% endblock %}

accounts/templates/accounts/organization_settings_lab_update.html
{% extends 'accounts/organization_settings_lab_detail.html' %}

{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% load hosts %}
{% load icons %}

{% block breadcrumb-tags %}
    {{ block.super }}
    {% breadcrumb 'Update' 'organization:lab:update' pk=organization.pk division='lab' %}
{% endblock %}

{% block profile-content-title %}Lab Settings{% endblock %}

{% block detail-actions-edit %}
    {% if perms.gist.change_lab %}
        {% host_url 'organization:lab:update' pk=organization.pk division='lab' host 'accounts' as url %}
        {% large_action_icon 'glyphicons-pencil' tooltip_message='Edit Lab' %}
    {% endif %}
{% endblock %}

{% block profile-content-body %}
    <form method='POST' action="{% host_url 'organization:lab:update' division='lab' pk=organization.pk host 'accounts' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <button type='submit' class='btn blue' name='Submit' value='Submit'>Submit</button>
    </form>
{% endblock %}

accounts/templates/accounts/organization_settings_update.html
{% extends 'accounts/organization_settings_detail.html' %}

{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% load hosts %}

{% block breadcrumb-tags %}
    {{ block.super }}
    {% breadcrumb 'Update' 'organization:settings:update' pk=organization.pk %}
{% endblock %}

{% block profile-content-title %}Settings{% endblock %}

{% block detail-actions-edit %}
    {% if perms.gist.change_organization %}
        {% host_url 'organization:settings:update' pk=organization.pk host 'accounts' as url %}
        {{ block.super }}
    {% endif %}
{% endblock %}

{% block profile-content-body %}
    <form action="{% host_url 'organization:settings:update' pk=organization.pk host 'accounts' %}" method='POST'>
        {% csrf_token %}
        <h4>General Information</h4>
        <p>{{ form.name|as_crispy_field}}</p>
        <p>{{ form.phone_number|as_crispy_field }}</p>
        <p>{{ form.fax_number|as_crispy_field }}</p>
        <p>{{ form.website|as_crispy_field }}</p>

        <h4>Address</h4>
        <p>{{ form.address_name|as_crispy_field }}</p>
        <p>{{ form.address_line1|as_crispy_field }}</p>
        <p>{{ form.address_line2|as_crispy_field }}</p>
        <p>{{ form.address_city|as_crispy_field }}</p>
        <p>{{ form.address_state|as_crispy_field }}</p>
        <p>{{ form.address_zip|as_crispy_field }}</p>
        <p>{{ form.address_country|as_crispy_field }}</p>
        <br>
        <button type='submit' class='btn blue' name='Submit' value='Submit'>Submit</button>
    </form>
{% endblock %}

accounts/templates/accounts/partials/_messages.html
{% if auth_state_missing %}
    <div class='alert alert-block alert-danger'><ul><li>We ran into a problem trying to log you in.<br/>Please try again!</li></ul></div>
{% elif activate_account %}
    <div class='alert alert-block alert-success'><ul><li>We are activating your account for the first time. Please check your email to set your password.</li></ul></div>
{% elif token_consumed %}
    <div class='alert alert-block alert-danger'><ul><li>Invite token has been used already.</li></ul></div>
{% elif invalid_token %}
    <div class='alert alert-block alert-danger'><ul><li>Invite token is invalid.</li></ul></div>
{% elif reset_email_sent %}
    <div class='alert alert-block alert-success'><ul><li>Check you email for your reset link.</li></ul></div>
{% elif password_reset %}
    <div class='alert alert-block alert-success'><ul><li>Your password has been successfully reset!</li></ul></div>
{% endif %}

accounts/templates/accounts/reset.html
{% extends 'accounts/base_form.html' %}

{% load crispy_forms_tags %}
{% load hosts %}

{% block html-title %}Reset Password{% endblock %}

{% block form %}
    <form id='login-form' action='{% host_url 'password_reset' host 'accounts' %}?token={{ request.GET.token }}' method='POST'>{% csrf_token %}

        {{ form|crispy }}

        <div id='login-button-container'>
            <button type='submit' class='btn btn-inverse'>Reset Password!</button>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/user_list.html
{% extends 'core/generics/base-list.html' %}

{% load django_bootstrap_breadcrumbs %}
{% load hosts %}
{% load icons %}

{% block accounts-app-navigation %}active{% endblock %}
{% block accounts-app-navigation-arrow %}open{% endblock %}

{% block breadcrumb-tags %}
    {% breadcrumb 'Accounts' 'root' %}
    {% breadcrumb 'Users' 'user:list' %}
{% endblock %}

{% block css-imports %}
    {{ block.super }}
    <style>
        #id-list-table {
            min-width: 1000px;
        }
    </style>
{% endblock %}

{% block html-title %}Users{% endblock %}

{% block page-title %}User List{% endblock %}

{% block list-actions-add %}
    {% if roles.gene_peeks_staff %}
        {% host_url 'user:create' host 'accounts' as url %}
        {% large_action_icon 'glyphicons-plus' tooltip_message='Add User' %}
    {% endif %}
{% endblock %}

{% block list-content %}
    {% with request.get_full_path as list_url %}
        <div id='id-list-table' class='row'>
            <div id="table" class="col-xs-10">
                {% include 'genepeeks/components/table.html' %}
            </div>
            <div class="col-xs-2">
                {% include 'genepeeks/components/filter.html' %}
            </div>
        </div>
    {% endwith %}
{% endblock %}

core/templates/core/columns/boolean.html
{% if value %}
    <span class="true">✔</span>
{% else %}
    <span class="false">✘</span>
{% endif %}

core/templates/core/generics/base-create.html
{% extends 'core/generics/base-update.html' %}

{% block form-caption %}Initialize & Create{% endblock %}

{% block update-actions-discard %}{% endblock %}

{% block form-button-text %}Create{% endblock %}